basePath: /
definitions:
  models.GameSession:
    type: object
  models.Quiz:
    type: object
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      role:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@quiz.com
    name: API Support
  description: REST API для управления квизами, пользователями и отчетами.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Quiz Platform Core API
  version: "1.0"
paths:
  /api/me:
    get:
      description: Возвращает данные текущего авторизованного пользователя
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Профиль пользователя
      tags:
      - Auth
  /api/quizzes:
    get:
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Quiz'
            type: array
      security:
      - BearerAuth: []
      summary: Список квизов преподавателя
      tags:
      - Quizzes
    post:
      consumes:
      - application/json
      description: Создает квиз с вопросами и вариантами ответов
      parameters:
      - description: Структура квиза
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Quiz'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Quiz'
        "400":
          description: Validation Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Создание Квиза
      tags:
      - Quizzes
  /api/quizzes/{id}:
    delete:
      parameters:
      - description: Quiz ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      summary: Удалить квиз
      tags:
      - Quizzes
    get:
      parameters:
      - description: Quiz ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Quiz'
      security:
      - BearerAuth: []
      summary: Получить квиз по ID
      tags:
      - Quizzes
    put:
      consumes:
      - application/json
      description: Полностью заменяет вопросы квиза на новые
      parameters:
      - description: Quiz ID
        in: path
        name: id
        required: true
        type: integer
      - description: Новая структура
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Quiz'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Quiz'
        "400":
          description: Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Обновление Квиза
      tags:
      - Quizzes
  /api/quizzes/public:
    get:
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Quiz'
            type: array
      security:
      - BearerAuth: []
      summary: Публичная библиотека квизов
      tags:
      - Quizzes
  /api/reports:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.GameSession'
            type: array
      security:
      - BearerAuth: []
      summary: История игр преподавателя
      tags:
      - Analytics
  /api/reports/{id}/export:
    get:
      parameters:
      - description: Session UUID
        in: path
        name: id
        required: true
        type: string
      produces:
      - text/csv
      responses:
        "200":
          description: OK
          schema:
            type: file
      security:
      - BearerAuth: []
      summary: Скачать CSV отчет
      tags:
      - Analytics
  /auth/change-password:
    post:
      consumes:
      - application/json
      parameters:
      - description: Смена пароля
        in: body
        name: input
        required: true
        schema:
          properties:
            new_password:
              type: string
            old_password:
              type: string
          type: object
      responses:
        "200":
          description: OK
        "400":
          description: Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Смена пароля
      tags:
      - Auth
  /auth/forgot-password:
    post:
      consumes:
      - application/json
      parameters:
      - description: Email
        in: body
        name: input
        required: true
        schema:
          properties:
            email:
              type: string
          type: object
      responses:
        "200":
          description: Instructions sent
          schema:
            type: string
      summary: Запрос на сброс пароля
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Возвращает JWT токен
      parameters:
      - description: Данные входа
        in: body
        name: input
        required: true
        schema:
          properties:
            email:
              type: string
            password:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              allOf:
              - type: string
              - properties:
                  token:
                    type: string
                type: object
            type: object
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Вход в систему
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Создает аккаунт преподавателя
      parameters:
      - description: Данные регистрации
        in: body
        name: input
        required: true
        schema:
          properties:
            email:
              type: string
            password:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Регистрация нового пользователя
      tags:
      - Auth
  /auth/reset-password:
    post:
      consumes:
      - application/json
      parameters:
      - description: Reset Data
        in: body
        name: input
        required: true
        schema:
          properties:
            new_password:
              type: string
            token:
              type: string
          type: object
      responses:
        "200":
          description: OK
        "400":
          description: Error
          schema:
            type: string
      summary: Установка нового пароля по токену
      tags:
      - Auth
  /internal/quizzes/{id}:
    get:
      parameters:
      - description: Quiz ID
        in: path
        name: id
        required: true
        type: integer
      - description: Secret Key
        in: header
        name: X-Internal-Secret
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Quiz'
      summary: 'INTERNAL: Получить квиз (для движка)'
      tags:
      - Internal
  /internal/reports:
    post:
      parameters:
      - description: Secret Key
        in: header
        name: X-Internal-Secret
        required: true
        type: string
      - description: Snapshot
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.GameSession'
      responses:
        "201":
          description: Created
      summary: 'INTERNAL: Сохранить результаты игры'
      tags:
      - Internal
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
